<?php
if( function_exists('acf_add_local_field_group') ):
  acf_add_local_field_group(array (
    'key' => 'group_580680050c149',
    'title' => 'Page Modulaire',
    'fields' => array (
      array (
        'key' => 'field_5806803664e6e',
        'label' => 'Bloc de contenu',
        'name' => 'content_blocks',
        'type' => 'flexible_content',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'button_label' => 'Ajoutez un module',
        'min' => '',
        'max' => '',
        'layouts' => array (
          // MODULE_SLIDER
          array (
            'key' => 'mod_slider',
            'title' => 'Slider',
            'label' => 'Slider accueil',
            'name' => 'slider_deux',
            'sub_fields' => array (
              array (
                'key' => 'optionfleche',
                'label' => 'Option flèche',
                'name' => 'preference_fleche',
                'type' => 'radio',
                'instructions' => 'Si le bloc affiche une image statique, assurez-vous de régler l\'option des flèches à "aucune"',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array (
                  '' => 'flèches',
                  'tparrowsnone' => 'aucune',
                ),
                'default_value' => array (
                ),
                'layout' => 'horizontal',
                'toggle' => 0,
              ),
              /*slide1*/
            array(
                  'key' => 'slideongletun',
                  'label' => 'Slide 1',
                  'name' => '',
                  'type' => 'tab',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'placement' => 'top',
                  'endpoint' => 0,
                  ),
              array (
                'key' => 'imagesliderun',
                'label' => 'Image background 1',
                'name' => 'image_background_un',
                'type' => 'image',
                'instructions' => '1920px par 1100px',
                'required' => 0,
                'conditional_logic' => 0,
                 'wrapper' => array (
                   'width' => '50',
                   'class' => '',
                   'id' => '',
                 ),
                 'return_format' => 'url',
                 'preview_size' => 'large',
                 'library' => 'all',
                 'min_width' => '',
                 'min_height' => '',
                 'min_size' => '',
                 'max_width' => '',
                 'max_height' => '',
                 'max_size' => '',
                 'mime_types' => '',
               ),
              array (
                'key' => 'imagecontenualtun',
                'label' => 'Contenu alt image 1',
                'name' => 'image_alt_un',
                'type' => 'text',
                'instructions' => 'Bonne pratique / référencement de l\'image',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'chiffreslideun_un',
                'label' => 'Chiffre identifiant précédent',
                'name' => 'chiffreslideun_un',
                'type' => 'text',
                'instructions' => 'Inscrire seulement un chiffre, s\'il s\'agit de la slide numéro 1, laisser le champs vide',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '12',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'chiffreslideun_deux',
                'label' => 'Chiffre identifiant suivant',
                'name' => 'chiffreslideun_deux',
                'type' => 'text',
                'instructions' => 'Inscrire seulement un chiffre, s\'il s\'agit de la slide numéro 4, laisser le champs vide',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '12',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'grostitreun',
                'label' => 'Titre prinipal 1 ',
                'name' => 'gros_titre_un',
                'type' => 'text',
                'instructions' => 'Ajouter la balise "br/" à l\'endroit ou vous voulez effectuer un saut de ligne',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '100',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'titreboutonun',
                'label' => 'Titre du bouton 1',
                'name' => 'titre_bouton_un',
                'type' => 'text',
                'instructions' => 'Inscrire le titre du bouton (n\'utilisez pas plus de 3 mots)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'lienboutonun',
                'label' => 'Lien 1',
                'name' => 'lien_bouton_un',
                'type' => 'text',
                'instructions' => 'Inscrire l\'url de destination',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'optionongletun',
                'label' => 'Préférence lien 1',
                'name' => 'preference_lien_un',
                'type' => 'radio',
                'instructions' => 'vous pouvez choisir d\'ouvrir le lien sur un nouvel onglet(lien externe) ou rediriger l\'utilisateur vers une autre page de votre site(lien interne)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array (
                  '_blank' => 'Lien externe',
                  '' => 'lien interne',
                ),
                'default_value' => array (
                ),
                'layout' => 'horizontal',
                'toggle' => 0,
              ),

              /*slide2*/
              array(
                    'key' => 'slideongletdeux',
                    'label' => 'Slide 2',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                  ),
            
              array (
                'key' => 'imagesliderdeux',
                'label' => 'Image background 2',
                'name' => 'image_background_deux',
                'type' => 'image',
                'instructions' => '1920px par 1100px',
                'required' => 0,
                'conditional_logic' => 0,
                 'wrapper' => array (
                   'width' => '75',
                   'class' => '',
                   'id' => '',
                 ),
                 'return_format' => 'url',
                 'preview_size' => 'large',
                 'library' => 'all',
                 'min_width' => '',
                 'min_height' => '',
                 'min_size' => '',
                 'max_width' => '',
                 'max_height' => '',
                 'max_size' => '',
                 'mime_types' => '',
               ),
              array (
                'key' => 'imagecontenualtdeux',
                'label' => 'contenu alt image 2',
                'name' => 'image_alt_deux',
                'type' => 'text',
                'instructions' => 'Bonne pratique / référencement de l\'image',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'chiffreslidedeuxun',
                'label' => 'chiffre identifiant précédent',
                'name' => 'chiffreslidedeux_un',
                'type' => 'text',
                'instructions' => 'Inscrire seulement un chiffre, s\'il s\'agit de la slide numéro 1, laisser le champs vide',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '12',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'chiffreslidedeuxdeux',
                'label' => 'chiffre identifiant suivant',
                'name' => 'chiffreslidedeux_deux',
                'type' => 'text',
                'instructions' => 'Inscrire seulement un chiffre, s\'il s\'agit de la slide numéro 4, laisser le champs vide',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '12',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'grostitredeux',
                'label' => 'Titre prinipal 2',
                'name' => 'gros_titre_deux',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '100',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'titreboutondeux',
                'label' => 'Titre du bouton 2',
                'name' => 'titre_bouton_deux',
                'type' => 'text',
                'instructions' => 'Inscrire le titre du bouton (n\'utilisez pas plus de 3 mots)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'lienboutondeux',
                'label' => 'Lien 2',
                'name' => 'lien_bouton_deux',
                'type' => 'text',
                'instructions' => 'Inscrire l\'url de destination',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'optionongletdeux',
                'label' => 'Préférence lien 2',
                'name' => 'preference_lien_deux',
                'type' => 'radio',
                'instructions' => 'vous pouvez choisir d\'ouvrir le lien sur un nouvel onglet(lien externe) ou rediriger l\'utilisateur vers une autre page de votre site(lien interne)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array (
                  '_blank' => 'Lien externe',
                  '' => 'lien interne',
                ),
                'default_value' => array (
                ),
                'layout' => 'horizontal',
                'toggle' => 0,
              ),
              /*slide3*/
              array(
                    'key' => 'slideonglettrois',
                    'label' => 'Slide 3',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                  ),
              
              array (
                'key' => 'imageslidertrois',
                'label' => 'Image background 3',
                'name' => 'image_background_trois',
                'type' => 'image',
                'instructions' => '1920px par 1100px',
                'required' => 0,
                'conditional_logic' => 0,
                 'wrapper' => array (
                   'width' => '75',
                   'class' => '',
                   'id' => '',
                 ),
                 'return_format' => 'url',
                 'preview_size' => 'large',
                 'library' => 'all',
                 'min_width' => '',
                 'min_height' => '',
                 'min_size' => '',
                 'max_width' => '',
                 'max_height' => '',
                 'max_size' => '',
                 'mime_types' => '',
               ),
              array (
                'key' => 'imagecontenualttrois',
                'label' => 'contenu alt image 3',
                'name' => 'image_alt_trois',
                'type' => 'text',
                'instructions' => 'Bonne pratique / référencement de l\'image',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'chiffreslidetrois_un',
                'label' => 'chiffre identifiant précédent',
                'name' => 'chiffreslidetrois_un',
                'type' => 'text',
                'instructions' => 'Inscrire seulement un chiffre, s\'il s\'agit de la slide numéro 1, laisser le champs vide',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '12',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'chiffreslidetrois_deux',
                'label' => 'chiffre identifiant suivant',
                'name' => 'chiffreslidetrois_deux',
                'type' => 'text',
                'instructions' => 'Inscrire seulement un chiffre, s\'il s\'agit de la slide numéro 4, laisser le champs vide',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '12',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'grostitredtrois',
                'label' => 'Titre prinipal 3',
                'name' => 'gros_titre_trois',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '100',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'titreboutontrois',
                'label' => 'Titre du bouton 3',
                'name' => 'titre_bouton_trois',
                'type' => 'text',
                'instructions' => 'Inscrire le titre du bouton (n\'utilisez pas plus de 3 mots)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'lienboutontrois',
                'label' => 'Lien 3',
                'name' => 'lien_bouton_trois',
                'type' => 'text',
                'instructions' => 'Inscrire l\'url de destination',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'optiononglettrois',
                'label' => 'Préférence lien 3',
                'name' => 'preference_lien_trois',
                'type' => 'radio',
                'instructions' => 'vous pouvez choisir d\'ouvrir le lien sur un nouvel onglet(lien externe) ou rediriger l\'utilisateur vers une autre page de votre site(lien interne)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array (
                  '_blank' => 'Lien externe',
                  '' => 'lien interne',
                ),
                'default_value' => array (
                ),
                'layout' => 'horizontal',
                'toggle' => 0,
              ),
              /*slide4*/
              array(
                    'key' => 'slideongletquatre',
                    'label' => 'Slide 4',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                  ),
              
              array (
                'key' => 'imagesliderquatre',
                'label' => 'Image background 4',
                'name' => 'image_background_quatre',
                'type' => 'image',
                'instructions' => '1920px par 1100px',
                'required' => 0,
                'conditional_logic' => 0,
                 'wrapper' => array (
                   'width' => '75',
                   'class' => '',
                   'id' => '',
                 ),
                 'return_format' => 'url',
                 'preview_size' => 'large',
                 'library' => 'all',
                 'min_width' => '',
                 'min_height' => '',
                 'min_size' => '',
                 'max_width' => '',
                 'max_height' => '',
                 'max_size' => '',
                 'mime_types' => '',
               ),
              array (
                'key' => 'imagecontenualtquatre',
                'label' => 'contenu alt image 4',
                'name' => 'image_alt_quatre',
                'type' => 'text',
                'instructions' => 'Bonne pratique / référencement de l\'image',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'chiffreslidequatre_un',
                'label' => 'chiffre identifiant précédent',
                'name' => 'chiffreslidequatre_un',
                'type' => 'text',
                'instructions' => 'Inscrire seulement un chiffre, s\'il s\'agit de la slide numéro 1, laisser le champs vide',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '12',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'chiffreslidequatre_deux',
                'label' => 'chiffre identifiant suivant',
                'name' => 'chiffreslidequatre_deux',
                'type' => 'text',
                'instructions' => 'Inscrire seulement un chiffre, s\'il s\'agit de la slide numéro 4, laisser le champs vide',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '12',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'grostitredquatre',
                'label' => 'Titre prinipal 4',
                'name' => 'gros_titre_quatre',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '100',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'titreboutonquatre',
                'label' => 'Titre du bouton 4',
                'name' => 'titre_bouton_quatre',
                'type' => 'text',
                'instructions' => 'Inscrire le titre du bouton (n\'utilisez pas plus de 3 mots)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'lienboutonquatre',
                'label' => 'Lien 4',
                'name' => 'lien_bouton_trois',
                'type' => 'text',
                'instructions' => 'Inscrire l\'url de destination',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'optionongletquatre',
                'label' => 'Préférence lien 4',
                'name' => 'preference_lien_quatre',
                'type' => 'radio',
                'instructions' => 'vous pouvez choisir d\'ouvrir le lien sur un nouvel onglet(lien externe) ou rediriger l\'utilisateur vers une autre page de votre site(lien interne)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array (
                  '_blank' => 'Lien externe',
                  '' => 'lien interne',
                ),
                'default_value' => array (
                ),
                'layout' => 'horizontal',
                'toggle' => 0,
              ),
            ),
          ),
          // MODULE_3_BLOCS_ENTETE
          array (
            'key' => 'mod_troisblocentete',
            'title' => '3 blocs',
            'label' => 'Entête / 3 blocs',
            'name' => '3_bloc_entete',
            'sub_fields' => array (
              /*boîte 1*/
              array(
                    'key' => 'boiteun',
                    'label' => 'Boîte 1',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                  ),
              
              array (
                'key' => 'imageboiteun',
                'label' => 'Image icône 1',
                'name' => 'image_icone_un',
                'type' => 'image',
                'instructions' => '40px 40px',
                'required' => 0,
                'conditional_logic' => 0,
                 'wrapper' => array (
                   'width' => '33',
                   'class' => '',
                   'id' => '',
                 ),
                 'return_format' => 'url',
                 'preview_size' => 'large',
                 'library' => 'all',
                 'min_width' => '',
                 'min_height' => '',
                 'min_size' => '',
                 'max_width' => '',
                 'max_height' => '',
                 'max_size' => '',
                 'mime_types' => '',
               ),
              array (
                'key' => 'boitegrostitre',
                'label' => 'Titre 1',
                'name' => 'boite_titre_un',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'boitesoustitreun',
                'label' => 'Sous-titre 1',
                'name' => 'boite_soustitre_un',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              /*boîte 2*/
              array(
                    'key' => 'boitedeux',
                    'label' => 'Boîte 2',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                  ),
              
              array (
                'key' => 'imageboitedeux',
                'label' => 'Image icône 2',
                'name' => 'image_icone_deux',
                'type' => 'image',
                'instructions' => '40px 40px',
                'required' => 0,
                'conditional_logic' => 0,
                 'wrapper' => array (
                   'width' => '33',
                   'class' => '',
                   'id' => '',
                 ),
                 'return_format' => 'url',
                 'preview_size' => 'large',
                 'library' => 'all',
                 'min_width' => '',
                 'min_height' => '',
                 'min_size' => '',
                 'max_width' => '',
                 'max_height' => '',
                 'max_size' => '',
                 'mime_types' => '',
               ),
              array (
                'key' => 'boitegrostitredeux',
                'label' => 'Titre 2',
                'name' => 'boite_titre_deux',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'boitesoustitredeux',
                'label' => 'Sous-titre 2',
                'name' => 'boite_soustitre_deux',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              /*boîte 3*/
              array(
                    'key' => 'boitetrois',
                    'label' => 'Boîte 3',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                  ),
              
              array (
                'key' => 'imageboitetrois',
                'label' => 'Image icône 3',
                'name' => 'image_icone_trois',
                'type' => 'image',
                'instructions' => '40px 40px',
                'required' => 0,
                'conditional_logic' => 0,
                 'wrapper' => array (
                   'width' => '33',
                   'class' => '',
                   'id' => '',
                 ),
                 'return_format' => 'url',
                 'preview_size' => 'large',
                 'library' => 'all',
                 'min_width' => '',
                 'min_height' => '',
                 'min_size' => '',
                 'max_width' => '',
                 'max_height' => '',
                 'max_size' => '',
                 'mime_types' => '',
               ),
              array (
                'key' => 'boitegrostitretrois',
                'label' => 'Titre 2',
                'name' => 'boite_titre_trois',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'boitesoustitretrois',
                'label' => 'Sous-titre 3',
                'name' => 'boite_soustitre_trois',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
            ),
          ),
          // MODULE_deux_images_textess
          array (
            'key' => 'mod_deuximagestexte',
            'title' => '2 images et texte',
            'label' => '2 images et textes',
            'name' => 'deux_images_texte',
            'sub_fields' => array (
 
              array (
                'key' => 'couleurdefonddeux',
                'label' => 'Couleur du background ',
                'name' => 'couleur_defond',
                'type' => 'radio',
                'instructions' => 'Choisir l\'alignement du texte',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '15',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array (
                  '#FFFFFF' => 'Blanc',
                  '#F7F7F7' => 'Gris pâle',
               
                ),
                'default_value' => array (
                ),
                'layout' => 'horizontal',
                'toggle' => 0,
              ),
              array (
                'key' => 'inversercolonne',
                'label' => 'Alignement colonne de texte',
                'name' => 'row_reverse',
                'type' => 'radio',
                'instructions' => 'Choisir l\'alignement du texte',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '15',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array (
                  'row-reverse' => 'Texte gauche',
                  '' => 'Texte droit',
               
                ),
                'default_value' => array (
                ),
                'layout' => 'horizontal',
                'toggle' => 0,
              ),
              array (
                'key' => 'GrostitreUn',
                'label' => 'OPTION SUR 2 LIGNES (titre ligne 1)',
                'name' => 'Grostitreun',
                'type' => 'text',
                'instructions' => 'Titre ligne 1',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '15',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
                array (
                  'key' => 'Grostitredeux',
                  'label' => 'OPTION SUR 2 LIGNES (titre ligne 2)',
                  'name' => 'Grostitredeux',
                  'type' => 'text',
                  'instructions' => 'Titre ligne 2',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '15',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                  'readonly' => 0,
                  'disabled' => 0,
                 ),
                array (
                  'key' => 'Grostitretrois',
                  'label' => 'OPTION SUR 1 LIGNES (Mauve)',
                  'name' => 'Grostitretrois',
                  'type' => 'text',
                  'instructions' => 'Titre sur une ligne mauve',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '15',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                  'readonly' => 0,
                  'disabled' => 0,
                 ),
                array (
                  'key' => 'optioinvertoubflanc',
                  'label' => 'Couleur image SVG ',
                  'name' => 'preference_svg',
                  'type' => 'radio',
                  'instructions' => 'choisir svg vert ou blanc',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '25',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array (
                    'imagedeux' => 'Blanc',
                    'imagetrois' => 'Vert',
                  ),
                  'default_value' => array (
                  ),
                  'layout' => 'horizontal',
                  'toggle' => 0,
                ),
              array (
                'key' => 'petitsoutitre',
                'label' => 'Sous titre',
                'name' => 'petit_soustitre',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '30',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'editeurdetextegros',
                'label' => 'Bloc de texte / grosse écriture',
                'name' => 'Bloc_texte_gros',
                'type' => 'wysiwyg',
                'instructions' => 'Éviter d"inscrire plus de 30 mots',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '30',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',  
                'media_upload' => 1,
              ),
              array (
                'key' => 'editeurdetextepetit',
                'label' => 'Bloc de texte',
                'name' => 'Bloc_texte_general',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '40',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
              ),
              array (
                'key' => 'titreboutonsavoirplus',
                'label' => 'Texte du bouton',
                'name' => 'texte_bouton',
                'type' => 'text',
                'instructions' => 'Inscrire le titre du bouton (n\'utilisez pas plus de 3 mots)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'lienboutontexte',
                'label' => 'lien',
                'name' => 'lien_savoir_plus',
                'type' => 'text',
                'instructions' => 'Inscrire l\'url de destination',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'optionongletsavoirplus',
                'label' => 'Préférence lien ',
                'name' => 'preference_lien_savoirplus',
                'type' => 'radio',
                'instructions' => 'vous pouvez choisir d\'ouvrir le lien sur un nouvel onglet(lien externe) ou rediriger l\'utilisateur vers une autre page de votre site(lien interne)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array (
                  '_blank' => 'Lien externe',
                  '' => 'lien interne',
                ),
                'default_value' => array (
                ),
                'layout' => 'horizontal',
                'toggle' => 0,
              ),
              array (
                'key' => 'imageparralaxun',
                'label' => 'Image parallax grande',
                'name' => 'image_parallax_un',
                'type' => 'image',
                'instructions' => '700px X 1027px',
                'required' => 0,
                'conditional_logic' => 0,
                 'wrapper' => array (
                   'width' => '25',
                   'class' => '',
                   'id' => '',
                 ),
                 'return_format' => 'url',
                 'preview_size' => 'large',
                 'library' => 'all',
                 'min_width' => '',
                 'min_height' => '',
                 'min_size' => '',
                 'max_width' => '',
                 'max_height' => '',
                 'max_size' => '',
                 'mime_types' => '',
               ),
              array (
                'key' => 'imagecontenualtparallaxgrande',
                'label' => 'contenu alt grande image',
                'name' => 'image_alt_parallax_grande',
                'type' => 'text',
                'instructions' => 'Bonne pratique / référencement de l\'image',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'imageparralaxdeux',
                'label' => 'Image parallax petite',
                'name' => 'image_parallax_deux',
                'type' => 'image',
                'instructions' => '317px X 477px',
                'required' => 0,
                'conditional_logic' => 0,
                 'wrapper' => array (
                   'width' => '25',
                   'class' => '',
                   'id' => '',
                 ),
                 'return_format' => 'url',
                 'preview_size' => 'large',
                 'library' => 'all',
                 'min_width' => '',
                 'min_height' => '',
                 'min_size' => '',
                 'max_width' => '',
                 'max_height' => '',
                 'max_size' => '',
                 'mime_types' => '',
               ),
              array (
                'key' => 'imagecontenualtparallaxpetite',
                'label' => 'Contenu alt petite image',
                'name' => 'image_alt_parallax_petite',
                'type' => 'text',
                'instructions' => 'Bonne pratique / référencement de l\'image',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '25',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'imagepartenaire',
                'label' => 'Logopartenaire',
                'name' => 'image_partenaire',
                'type' => 'image',
                'instructions' => 'OPTIONNEL',
                'required' => 0,
                'conditional_logic' => 0,
                 'wrapper' => array (
                   'width' => '100',
                   'class' => '',
                   'id' => '',
                 ),
                 'return_format' => 'url',
                 'preview_size' => 'large',
                 'library' => 'all',
                 'min_width' => '',
                 'min_height' => '',
                 'min_size' => '',
                 'max_width' => '',
                 'max_height' => '',
                 'max_size' => '',
                 'mime_types' => '',
               ),
              array (
                'key' => 'altlogopartenaire',
                'label' => 'Img alt',
                'name' => 'altlogopartenaire',
                'type' => 'text',
               'instructions' => 'Bonne pratique / référencement de l\'image',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'classpaddingdesssuximages',
                'label' => 'Espacement section ',
                'name' => 'espacement_section',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array (
                   '' => 'Aucun espace',
                  'espacementsection_un' => 'Espacement',
                 
               
                ),
                'default_value' => array (
                ),
                'layout' => 'horizontal',
                'toggle' => 0,
              ),
            ),
          ),
          // MODULE_CTA
          array (
            'key' => 'mod_cta',
            'title' => 'CTA',
            'label' => 'Appel à l\'action CTA',
            'name' => 'cta',
            'sub_fields' => array (
              array (
                'key' => 'imagebackgroundcta',
                'label' => 'Image de fond',
                'name' => 'image_CTA',
                'type' => 'image',
                'instructions' => '317px X 477px',
                'required' => 0,
                'conditional_logic' => 0,
                 'wrapper' => array (
                   'width' => '50',
                   'class' => '',
                   'id' => '',
                 ),
                 'return_format' => 'url',
                 'preview_size' => 'large',
                 'library' => 'all',
                 'min_width' => '',
                 'min_height' => '',
                 'min_size' => '',
                 'max_width' => '',
                 'max_height' => '',
                 'max_size' => '',
                 'mime_types' => '',
               ),
              array (
                'key' => 'grostitreCTA',
                'label' => 'Sous titre',
                'name' => 'titre_CTA',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '50',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'titreboutonCTA',
                'label' => 'Texte du bouton',
                'name' => 'texte_boutonCTA',
                'type' => 'text',
                'instructions' => 'Inscrire le titre du bouton (n\'utilisez pas plus de 3 mots)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
               ),
              array (
                'key' => 'lienboutontextecta',
                'label' => 'lien',
                'name' => 'lien_savoir_plus_cta',
                'type' => 'text',
                'instructions' => 'Inscrire l\'url de destination',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'optionongletsavoirpluscta',
                'label' => 'Préférence lien ',
                'name' => 'preference_lien_savoirplus_cta',
                'type' => 'radio',
                'instructions' => 'vous pouvez choisir d\'ouvrir le lien sur un nouvel onglet(lien externe) ou rediriger l\'utilisateur vers une autre page de votre site(lien interne)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array (
                  '_blank' => 'Lien externe',
                  '' => 'lien interne',
                ),
                'default_value' => array (
                ),
                'layout' => 'horizontal',
                'toggle' => 0,
              ),
            ),
          ),
          // TROIS NOUVELLES
          array (
            'key' => 'mod_troisnouvelles',
            'title' => 'Dernières nouvelles',
            'label' => '3 dernières nouvelles',
            'name' => 'trois_nouvelles',
            'sub_fields' => array (
            ),
          ),
          // VIDÉO IMAGES
          array (
            'key' => 'mod_textevideo',
            'title' => 'Vidéo et texte',
            'label' => '2 colonnes / Vidéo',
            'name' => 'texte_video',
            'sub_fields' => array (
              array (
                  'key' => 'textevideopetittitre',
                  'label' => 'Petit titre',
                  'name' => 'textevideopetitT',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '40',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                  'readonly' => 0,
                  'disabled' => 0,
                ),
              array (
                  'key' => 'textevideogrostitre',
                  'label' => 'Gros titre',
                  'name' => 'textevideopgrosT',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '40',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                  'readonly' => 0,
                  'disabled' => 0,
                ),
              array (
                'key' => 'textvideobloctexte',
                'label' => 'Bloc de texte',
                'name' => 'bloctextevideo3',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '40',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',  
                'media_upload' => 1,
              ),
            ),
          ),
          /*2 colonnes*/
          array (
            'key' => 'mod_bloc2colonnes',
            'title' => 'Bloc 2 colonnes',
            'label' => '2 colonnes',
            'name' => 'deux_colonnes',
            'sub_fields' => array (
              array (
                'key' => 'optioncouleurdefonddeux',
                'label' => 'Couleur background',
                'name' => 'preference_backgroundcolor_deux_colonnes',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '30',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array (
                  '#FFFFFF' => 'Blanc',
                  '#F7F7F7' => 'Gris pâle',
                  '#C9D63B10' => 'Vert pâle',
                ),
                'default_value' => array (
                ),
                'layout' => 'horizontal',
                'toggle' => 0,
              ),
              array (
                'key' => 'optionbordessr',
                'label' => 'Bordure grise',
                'name' => 'optionbordure',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '30',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array (
                  '' => 'Non',
                  'bordurecolonnes' => 'Bordure',
 
                ),
                'default_value' => array (
                ),
                'layout' => 'horizontal',
                'toggle' => 0,
              ),
              array (
                'key' => 'paddingbotton130',
                'label' => 'Espacement bas de section',
                'name' => 'paddingbottom',
                'type' => 'radio',
                'instructions' => 'ajouter un espacement en bas de la section',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '30',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array (
                  '' => 'Non',
                  'paddingbottomdeuxcolonnes' => 'oui',
              
                ),
                'default_value' => array (
                ),
                'layout' => 'horizontal',
                'toggle' => 0,
              ),
              array (
                  'key' => 'textedeuxcolonnesderoit1',
                  'label' => 'Sous titre',
                  'name' => 'soustitredroit_2col',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '40',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                  'readonly' => 0,
                  'disabled' => 0,
                ),
              array (
                'key' => 'editeurdetextedeuxcolonnesdroit',
                'label' => 'Bloc de texte',
                'name' => 'Bloc_textedroit_col_2',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '40',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',  
                'media_upload' => 1,
              ),
              array (
                  'key' => 'textedeuxcolonnesderoit2',
                  'label' => 'Sous titre',
                  'name' => 'soustitregauche_2col',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '40',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                  'readonly' => 0,
                  'disabled' => 0,
                ),
              array (
                'key' => 'editeurdetextedeuxcolonnesdroit2',
                'label' => 'Bloc de texte',
                'name' => 'Bloc_textegauche_col_2',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '40',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',  
                'media_upload' => 1,
              ),


            ),
          ),
          // TROIS carousel
          array (
            'key' => 'mod_carousel',
            'title' => 'Carousel',
            'label' => 'Bloc carousel',
            'name' => 'carousel',
            'sub_fields' => array (
              array (
                'key' => 'optioncouleurdefond',
                'label' => 'Couleur background',
                'name' => 'preference_backgroundcolor',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '20',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array (
                  '#FFFFFF' => 'Blanc',
                  '#F7F7F7' => 'Gris pâle',
                  '#C9D63B10' => 'Vert pâle',
                ),
                'default_value' => array (
                ),
                'layout' => 'horizontal',
                'toggle' => 0,
              ),
              array (
                  'key' => 'textedroitcarousel',
                  'label' => 'Sous titre',
                  'name' => 'soustitredroit_carousel',
                  'type' => 'text',
                  'instructions' => '',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '40',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                  'readonly' => 0,
                  'disabled' => 0,
                ),
              array (
                'key' => 'editeurdetextedroitcarousel',
                'label' => 'Bloc de texte',
                'name' => 'Bloc_textedroit_carousel',
                'type' => 'wysiwyg',
                'instructions' => 'Éviter d"inscrire plus de 100 mots',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '40',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',  
                'media_upload' => 1,
              ),
              array (
              'key' => 'bloc_carousel',
              'label' => 'Bloc répétitif ',
              'name' => 'bloccarousel',
              'type' => 'repeater',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'collapsed' => '',
              'min' => '',
              'max' => '',
              'layout' => 'block',
              'button_label' => 'Ajouter une image',
              'sub_fields' => array (

                array (
                  'key' => 'imagecarouselun',
                  'label' => 'Image défilante',
                  'name' => 'image_defilante',
                  'type' => 'image',
                  'instructions' => '800px X 622px',
                  'required' => 0,
                  'conditional_logic' => 0,
                   'wrapper' => array (
                     'width' => '30',
                     'class' => '',
                     'id' => '',
                   ),
                   'return_format' => 'url',
                   'preview_size' => 'large',
                   'library' => 'all',
                   'min_width' => '',
                   'min_height' => '',
                   'min_size' => '',
                   'max_width' => '',
                   'max_height' => '',
                   'max_size' => '',
                   'mime_types' => '',
                 ),
                array (
                    'key' => 'soustitrecarousel',
                    'label' => 'Sous titre',
                    'name' => 'soustitre_carousel',
                    'type' => 'text',
                    'instructions' => 'Ajouter la balise "br/" à l\'endroit ou vous voulez effectuer un saut de ligne',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                      'width' => '40',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                  ),
                array (
                    'key' => 'altimagecarousel',
                    'label' => '  Texte alternatif image',
                    'name' => 'altimagecarousel',
                    'type' => 'text',
                    'instructions' => 'Ce champs a pour but de référencer l\'image, veuillez décrire la photo en 2 ou 3 mots.. ce texte ne sera pas visible mais sera bénéfique pour les moteurs de recherche',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                      'width' => '30',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                  ),
              ),
            ),
          ),
        ),
          // banner
          array (
            'key' => 'mod_banner',
            'title' => 'Bannière',
            'label' => 'Bannière secondaire',
            'name' => 'banner',
            'sub_fields' => array (
            ),
          ),
          // FORMULAIRE VIDÉOS
          array (
            'key' => 'mod_formulairevideos',
            'title' => 'Bloc vidéo et formulaire',
            'label' => 'Vidéos et formulaire',
            'name' => 'Formulaire_et_video',
            'sub_fields' => array (
              array (
                'key' => 'imagebackgroundvideo',
                'label' => 'Image de fond',
                'name' => 'image_video',
                'type' => 'image',
                'instructions' => '1920px X 1100px',
                'required' => 0,
                'conditional_logic' => 0,
                 'wrapper' => array (
                   'width' => '50',
                   'class' => '',
                   'id' => '',
                 ),
                 'return_format' => 'url',
                 'preview_size' => 'large',
                 'library' => 'all',
                 'min_width' => '',
                 'min_height' => '',
                 'min_size' => '',
                 'max_width' => '',
                 'max_height' => '',
                 'max_size' => '',
                 'mime_types' => '',
               ),
              array (
                'key' => 'imageformulaire',
                'label' => 'Image infolettre',
                'name' => 'image_infolettre',
                'type' => 'image',
                'instructions' => '800x X 840px',
                'required' => 0,
                'conditional_logic' => 0,
                 'wrapper' => array (
                   'width' => '50',
                   'class' => '',
                   'id' => '',
                 ),
                 'return_format' => 'url',
                 'preview_size' => 'large',
                 'library' => 'all',
                 'min_width' => '',
                 'min_height' => '',
                 'min_size' => '',
                 'max_width' => '',
                 'max_height' => '',
                 'max_size' => '',
                 'mime_types' => '',
               ),

            ),
          ),
          // ÉQUIPE
          array (
            'key' => 'blocequipe',
            'title' => 'Bloc Équipe',
            'label' => 'Équipe',
            'name' => 'team',
            'sub_fields' => array (
              array (
                'key' => 'backgroundcolorequipe',
                'label' => 'Couleur de fond',
                'name' => 'bg_colorequipe',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array (
                  '#F7F7F7' => 'Gris pâle',
                  '#FFFFFF' => 'Blanc',
                ),
                'default_value' => array (
                ),
                'layout' => 'horizontal',
                'toggle' => 0,
              ),
              array (
              'key' => 'bloc_equipe',
              'label' => 'Équipe ',
              'name' => 'blocequipe',
              'type' => 'repeater',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'collapsed' => '',
              'min' => '',
              'max' => '',
              'layout' => 'block',
              'button_label' => 'Ajouter un membre',
              'sub_fields' => array (
              array (
                'key' => 'imageequipe',
                'label' => 'Portrait',
                'name' => 'image_portrait',
                'type' => 'image',
                'instructions' => '525px X 639px',
                'required' => 0,
                'conditional_logic' => 0,
                 'wrapper' => array (
                   'width' => '50',
                   'class' => '',
                   'id' => '',
                 ),
                 'return_format' => 'url',
                 'preview_size' => 'large',
                 'library' => 'all',
                 'min_width' => '',
                 'min_height' => '',
                 'min_size' => '',
                 'max_width' => '',
                 'max_height' => '',
                 'max_size' => '',
                 'mime_types' => '',
               ),
              array (
                  'key' => 'altimageeuiqpe',
                  'label' => 'text alternatif image',
                  'name' => 'altequipe',
                  'type' => 'text',
                  'instructions' => 'Ce champs a pour but de référencer l\'image, veuillez décrire la photo en 2 ou 3 mots.. ce texte ne sera pas visible mais sera bénéfique pour les moteurs de recherche',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array (
                    'width' => '15',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => '',
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'maxlength' => '',
                  'readonly' => 0,
                  'disabled' => 0,
                ),
              array (
                'key' => 'equipesoustitre',
                'label' => 'Nom',
                'name' => 'euipe_nom',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),
              array (
                'key' => 'equipetitre',
                'label' => 'Nom',
                'name' => 'euipe_titre',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '33',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
                'readonly' => 0,
                'disabled' => 0,
              ),

              ),
            ),
                ),
              ),
            
          // Témoignages
          array (
            'key' => 'mod_temoignage',
            'title' => 'Bloc témoignages',
            'label' => 'Témoignages',
            'name' => 'temoignages',
            'sub_fields' => array (
                      array (
                'key' => 'bloc_temoignage',
                'label' => 'Carousel ',
                'name' => 'bloctemoignage',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'collapsed' => '',
                'min' => '',
                'max' => '',
                'layout' => 'block',
                'button_label' => 'Ajouter un témoignage',
                'sub_fields' => array (
              
                  array (
                    'key' => 'photocarouseltemoignage',
                    'label' => 'Photo',
                    'name' => 'photo_carousel',
                    'type' => 'image',
                    'instructions' => '634x612px, 72dpi',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                      'width' => '20',
                      'class' => '',
                      'id' => '',
                    ),
                    'return_format' => 'url',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                  ),
                  array (
                    'key' => 'courttextecarousel',
                    'label' => 'Sous-titre',
                    'name' => 'carouselbold',
                    'type' => 'text',
                    'instructions' => 'Inscrire l\'url de destination',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                      'width' => '33',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                    'readonly' => 0,
                    'disabled' => 0,
                  ),

                    array (
                        'key' => 'altimagecarousel',
                        'label' => 'text alternatif image',
                        'name' => 'altcarousel',
                        'type' => 'text',
                        'instructions' => 'Ce champs a pour but de référencer l\'image, veuillez décrire la photo en 2 ou 3 mots.. ce texte ne sera pas visible mais sera bénéfique pour les moteurs de recherche',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                          'width' => '15',
                          'class' => '',
                          'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                      ),
                    array (
                      'key' => 'editeurdetextecarousel',
                      'label' => 'Bloc de texte',
                      'name' => 'Bloc_texte_carousel',
                      'type' => 'wysiwyg',
                      'instructions' => 'Éviter d"inscrire plus de 30 mots',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array (
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'tabs' => 'all',
                      'toolbar' => 'full',  
                      'media_upload' => 1,
                    ),
                    array (
                        'key' => 'carouselnom',
                        'label' => 'Nom',
                        'name' => 'carouselnom',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                          'width' => '25',
                          'class' => '',
                          'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                      ),
                    array (
                        'key' => 'carouseltitre',
                        'label' => 'fonction',
                        'name' => 'carouseltitre',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                          'width' => '25',
                          'class' => '',
                          'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                        'readonly' => 0,
                        'disabled' => 0,
                      ),
               
              
              
                   ),
                 ),
              
            ),
          ),
    
        ),
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'page',
        ),
      ),

      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'block',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array (
      0 => 'the_content',
    ),
    'active' => 1,
    'description' => '',
  ));
endif;
